config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :plants do
    resources :rentings, only: [:create]
  end
  resources :rentings, only: [:show, :destroy] do
    member do
      patch :accept
      patch :deny
    end
  end
  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord

  belongs_to :user
  has_many :rentings
  has_many_attached :photos

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_category_description,
    against: [:name, :category, :description],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :plant
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :end_date_cannot_be_before_start_date
  validates :status, presence: true, inclusion: { in: ['Demande en attente', 'Demande acceptée', 'Demande refusée'] }

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "ne peut pas être dans le passé") if
      !start_date.blank? && start_date < Date.today
  end

  def end_date_cannot_be_before_start_date
    errors.add(:end_date, "ne peut pas être avant la date de début de location") if
      end_date < start_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plants
  has_many :rentings
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  def home
  end

  def dashboard
    @user = current_user
    @own_plants = @user.plants
    @rentings = @user.rentings
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @plants = Plant.all

    if params[:query].present?
      @plants = Plant.search_by_name_category_description(params[:query])
    else
      @plants = Plant.all
    end

    if params[:filter].present?
      @plants = @plants.where(category: params[:filter])
    end

    @page = [params[:page].to_i, 1].max
    @per_page = 6
    @total_count = @plants.count
    @total_pages = (@total_count.to_f / @per_page).ceil
    @plants = @plants.offset((@page - 1) * @per_page).limit(@per_page)
  end

  def show
    @plant = Plant.find(params[:id])
    @renting = Renting.new
    @user = current_user
    @plant_user = @plant.user
    if @plant_user.latitude && @plant_user.longitude
      @markers =
        [{
          lat: @plant_user.latitude,
          lng: @plant_user.longitude
        }]
      else
        @markers = []
    end
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(new_params)
    @plant.user = current_user
    if @plant.save
      redirect_to plant_path(@plant), notice: 'La plante a été créée avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    if @plant.update(plants_params)
      redirect_to plant_path(@plant), notice: 'Annonce mise à jour avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def plants_params
    params.require(:plant).permit(:name, :category, :description, :price, :photos)
  end

  def new_params
    params.require(:plant).permit(:name, :category, :description, :price, photos:[])
  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :set_renting, only: [:accept, :deny]

  def create
    @renting = Renting.new(renting_params)
    @renting.user = current_user
    plant = Plant.find(params[:plant_id])
    @renting.plant = plant
    @renting.status = 'Demande en attente'

    if @renting.save
      redirect_to plant_path(plant), notice: "Votre demande de réservation a été envoyée avec succès."
    else
      render :show, alert: "Il y a eu un problème avec votre demande de réservation."
    end
  end

  def accept
    if @renting.update!(status: 'Demande acceptée')
      redirect_to dashboard_path, notice: 'La demande a été acceptée'
    else
      redirect_to dashboard_path, alert: 'Il y a eu une erreur'
    end
  end

  def deny

    if @renting.update!(status: 'Demande refusée')
      redirect_to dashboard_path, notice: 'La demande a été refusée'
    else
      redirect_to dashboard_path, alert: 'Il y a eu une erreur'
    end
  end

  private

  def renting_params
    params.require(:renting).permit(:start_date, :end_date)
  end

  def set_renting
    @renting = Renting.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantyProject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">

  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% elsif alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mb-3" style="margin-top: 84px">
  <h1 class="text-primary my-4">Dashboard</h1>
  <div class="card mb-4 py-2" style="background: #FEF6EF; border-radius: 10px; border-color: #8E5018">
    <div class="d-flex">
      <%= cl_image_tag @user.photo.key, gravity: :face, class: "rounded-circle m-4 border border-secondary-subtle border-opacity-50 my-auto", style: "width: 140px; object-fit: cover; height: 140px;" %>
      <div class="card-body">
        <h5 class="card-title fw-bold fs-3"><%= @user.first_name %> <%= @user.last_name %></h5>
        <p class="card-text mb-1">Membre de Planty depuis <%= @user.created_at.year %></p>
        <p class="card-text mb-1"><%= @user.address %></p>
        <p class="card-text"><%= @user.email %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card shadow" style="border-radius: 10px">
        <div class="card-body">
          <h5 class="card-title fw-bold fs-3 border-bottom pb-3 text-center text-primary">Tes plantes</h5>
          <% @own_plants.each do |plant| %>
            <div class="d-flex mt-4">
              <%= cl_image_tag plant.photos.first.key, class: "rounded-circle m-4 my-auto", style: "width: 50px; object-fit: cover; height: 50px;" %>
              <%= link_to plant.name, plant_path(plant), class: "text-dark text-decoration-none align-self-center" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow" style="border-radius: 10px">
        <div class="card-body">
          <h5 class="card-title fw-bold fs-3 border-bottom pb-3 text-center text-primary">Demandes de location</h5>
          <% @own_plants.each do |plant| %>
            <% requests = plant.rentings %>
            <% requests.each do |request| %>
              <div class="d-flex mt-4">
                <% if request.status == 'Demande en attente' %>
                  <i class="fa-solid fa-circle align-content-around" style="color: #EDD245"></i>
                  <button class="btn btn-link text-start text-decoration-none text-dark" data-bs-target="#rentingRequestPending-<%=request.id %>" data-bs-toggle="modal" type="button"><%= request.status %> pour <%= plant.name %></button>
                <% elsif request.status == 'Demande acceptée' %>
                  <i class="fa-solid fa-circle align-content-around" style="color: #34CA55"></i>
                  <button class="btn btn-link text-start text-decoration-none text-dark" data-bs-target="#rentingRequestAccepted" data-bs-toggle="modal" type="button"><%= request.status %> pour <%= plant.name %></button>
                <% else %>
                  <i class="fa-solid fa-circle align-content-around" style="color: #CA5834"></i>
                  <button class="btn btn-link text-start text-decoration-none text-dark" data-bs-target="#rentingRequestRefused" data-bs-toggle="modal" type="button"><%= request.status %> pour <%= plant.name %></button>
                <% end %>
                <!-- Modal Pending -->
                <div class="modal fade" id="rentingRequestPending-<%=request.id %>" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content px-3">
                      <div class="modal-header">
                        <h1 class="modal-title fs-4 fw-bold text-primary" id="modalTitle"><%= request.status %> pour <%= plant.name %></h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="d-flex border border-secondary-subtle py-3" style="border-radius: 10px">
                          <%= cl_image_tag request.user.photo.key, gravity: :face, class: "rounded-circle m-4 border border-secondary-subtle border-opacity-50 my-auto", style: "width: 100px; object-fit: cover; height: 100px;" %>
                          <div class="div">
                            <p class="fs-3 m-0 text-dark-emphasis"><%= request.user.first_name %> <%= request.user.last_name %></p>
                            <p class="fst-italic m-0">Je veux louer ta plante</p>
                            <div class="d-flex">
                              <p class="fw-bold m-0 pe-2">Date de début :</p>
                              <p class="m-0"><%= request.start_date.day %>/<%= request.start_date.month %>/<%= request.start_date.year %></p>
                            </div>
                            <div class="d-flex">
                              <p class="fw-bold m-0 pe-2">Date de fin :</p>
                              <p class="m-0"><%= request.end_date.day %>/<%= request.end_date.month %>/<%= request.end_date.year %></p>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="d-flex justify-content-center mb-4">
                        <%= link_to "Refuser", deny_renting_path(request), data: { 'turbo-method' => :patch }, class: "btn me-5 rounded-pill",
                                                                                        style: "background: #F6CCCC;
                                                                                                width: 120px;
                                                                                                color: #CA5834" %>
                        <%= link_to "Accepter", accept_renting_path(request), data: { 'turbo-method' => :patch },
                                                                              class: "btn btn-primary ms-5 rounded-pill text-white",
                                                                              style: "width: 120px" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow" style="border-radius: 10px">
        <div class="card-body">
          <h5 class="card-title fw-bold fs-3 border-bottom pb-3 text-center text-primary">Plantes louées</h5>
          <% @rentings.each do |renting| %>
            <div class="d-flex border border-secondary-subtle py-2 mb-2" style="border-radius: 10px">
              <%= cl_image_tag renting.plant.photos.first.key, class: "rounded-circle m-4 my-auto", style: "width: 50px; object-fit: cover; height: 50px;" %>
              <div>
                <p class="m-0 fw-bold"><%= renting.plant.name %></p>
                <p class="m-0"><%= renting.start_date.day %>/<%= renting.start_date.month %>/<%= renting.start_date.year %> - <%= renting.end_date.day %>/<%= renting.end_date.month %>/<%= renting.end_date.year %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid hero" style="margin-top: 60px">
  <div class="hero-text">
    <h1>Bienvenue sur Planty</h1>
    <p>Planty, votre solution simple pour louer des plantes</p>
    <%= link_to 'Entrez', plants_path, class: 'btn btn-primary', type: 'button'%>
  </div>
</div>

app/views/plants/edit.html.erb
<div class="container" style ="margin-top: 84px">
  <h1 class="text-center my-4 text-primary">Modifier l'article</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card p-4">
        <%= simple_form_for(@plant) do |f| %>

          <div class="mb-3">
            <%= f.label "Name :", class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Catégorie :', class: 'form-label' %>
            <%= f.text_field :category, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Description :', class: 'form-label' %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Prix :', class: 'form-label' %>
            <%= f.number_field :price, class: 'form-control' %>
          </div>
          <div class="text-center">
            <%= f.button :submit, "Mettre à jour", class: "btn btn-primary p-0" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<div class="container-banner" style="margin-top: 60px">
  <div class="banner">
    <nav class="searchbar-index d-flex justify-content-center align-items-center position-relative">
      <div class="input-wrapper position-relative">
        <%= form_tag plants_path, method: :get, class: "form-inline" do %>
          <%= text_field_tag :query, params[:query], class: "form-control-index", placeholder: "Trouvez votre plante !" %>
          <button class="clear-btn" style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%); border: none; background: none;">x</button>
        <% end %>
      </div>
    </nav>
  </div>
</div>

<div class="container-filter">
  <div class="banner-filter container-fluid d-flex align-items-center">
    <%= link_to plants_path(filter: params[:filter] == "Purificateur" ? nil : "Purificateur", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn1 <%= 'active' if params[:filter] == 'Purificateur' %>"></button>
      <p class="filter-text">Purificateur</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == 'Purificateur'}" %>
    <% end %>

    <%= link_to plants_path(filter: params[:filter] == "Humidificateur" ? nil : "Humidificateur", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn2 <%= 'active' if params[:filter] == 'Humidificateur' %>"></button>
      <p class="filter-text">Humidificateur</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == 'Humidificateur'}" %>
    <% end %>

    <%= link_to plants_path(filter: params[:filter] == "Déhumidificateur" ? nil : "Déhumidificateur", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn3 <%= 'active' if params[:filter] == 'Déhumidificateur' %>"></button>
      <p class="filter-text">Déhumidificateur</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == 'Déhumidificateur'}" %>
    <% end %>

    <%= link_to plants_path(filter: params[:filter] == "Remonte l'humeur" ? nil : "Remonte l'humeur", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn4 <%= 'active' if params[:filter] == "Remonte l'humeur" %>"></button>
      <p class="filter-text">Remonte l'humeur</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == "Remonte l'humeur"}" %>
    <% end %>

    <%= link_to plants_path(filter: params[:filter] == "Tropical" ? nil : "Tropical", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn5 <%= 'active' if params[:filter] == 'Tropical' %>"></button>
      <p class="filter-text">Tropical</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == 'Tropical'}" %>
    <% end %>

    <%= link_to plants_path(filter: params[:filter] == "Grasse" ? nil : "Grasse", query: params[:query]), class: "filter-link" do %>
      <button class="filter-btn filter-btn6 <%= 'active' if params[:filter] == 'Grasse' %>"></button>
      <p class="filter-text">Grasse</p>
      <%= content_tag :div, '', class: "filter-bar #{'active-bar' if params[:filter] == 'Grasse'}" %>
    <% end %>
  </div>
</div>


<div class="container-card-index">
  <% @plants.each_with_index do |plant, index| %>
    <%= link_to plant_path(plant), class:"text-decoration-none" do %>
    <div class="card-index">
      <div id="carouselExample<%= index + 1 %>" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% plant.photos.each_with_index do |photo, img_index| %>
            <div class="carousel-item <%= 'active' if img_index == 0 %>">
              <%= cl_image_tag photo.key, class: "d-block w-100 good-image" %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%= index + 1 %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%= index + 1 %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-index-body">
        <h5 class="card-index-title"><%= plant.name %></h5>
        <p class="card-index-text text-dark"><%= plant.description %></p>
      </div>
    <% end %>
      <div class="details-price-card-index container-fluid d-flex align-items-end justify-content-between">
        <a href="<%= plant_path(plant) %>" class="btn btn-primary mb-1">Détails</a>
        <p class="card-index-price mb-0"><%= plant.price %>€ / par jour</p>
      </div>
    </div>
  <% end %>
</div>

<div class="pagination-index d-flex justify-content-center align-items-center">
  <% (1..@total_pages).each do |page| %>
    <a href="<%= plants_path(page: page, filter: params[:filter]) %>" class="pagination-index-link <%= 'active' if page == @page %>">
      <%= page %>
    </a>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="container" style ="margin-top: 84px">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
  <h1 class="text-center my-4 text-primary">Créer une nouvelle annonce</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card p-4">
        <%= simple_form_for(@plant) do |f| %>

          <div class="mb-3">
            <%= f.label 'Nom :', class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Catégorie :', class: 'form-label' %>
            <%= f.text_field :category, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Description :', class: 'form-label' %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>

          <div class="mb-3">
            <%= f.label 'Prix :', class: 'form-label' %>
            <%= f.number_field :price, class: 'form-control' %>
          </div>
          <div class="mb-3">
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          </div>
          <div class="text-center">
            <%= f.submit 'Créer', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container" style="margin-top: 84px">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
      <div class="row">
          <!-- Left Content -->
          <div class="col-md-8">
              <div class="card mb-3">
                    <!-- Carrousel -->
                <div id="carouselExample<%= @plant.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    <% @plant.photos.each_with_index do |photo, img_index| %>
                      <div class="carousel-item <%= 'active' if img_index == 0 %>">
                        <%= cl_image_tag photo.key, class: "d-block w-100 custom-carousel-image", crop: "pad", width: 750, height: 375, background: "auto", alt: @plant.name %>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%= @plant.id %>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%= @plant.id %>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
                <!-- Fin du Carrousel -->
                <div class="card-show">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <h5 class="card-title text-primary fs-1 fw-bold"> <%= @plant.name %>
                      </h5>
                          <% if @plant.user == @user %>
                        <%= link_to 'Modifier', edit_plant_path(@plant), class: 'btn btn-primary', type: 'button'%>
                          <% end %>
                    </div>
                      <p class="card-text text-muted fst-italic"> <%= @plant.category %> </p>
                      <p class="card-text">
                          <%= @plant.description %>
                      </p>
                      <div class="d-flex align-items-center border mt-2 p-2" style="border-radius: 10px;">
                        <%= cl_image_tag @plant.user.photo.key, gravity: :face, class: "rounded-circle m-4 border border-secondary-subtle border-opacity-50 my-auto", style: "width: 80px; object-fit: cover; height: 80px;" %>
                        <div>
                          <strong> <%= @plant.user.first_name %> </strong><br>
                          <small>Membre de Planty depuis <%= @plant.user.created_at.year %></small><br>
                          <small><%= @plant.user.address %></small>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
          </div>
          <div class="col-md-4">
  <!-- Card pour la carte -->
  <% if @plant.user.latitude && @plant.user.longitude %>
    <div class="card shadow-sm p-3 mb-1 bg-white rounded">
      <div id="map" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"  data-map-markers-value="<%= @markers.to_json %>"
       style="height: 165px;"></div>
    </div>
  <% else %>
    <div class="card shadow-sm p-3 mb-3 bg-white rounded">
      <p>L'adresse n'a pas pu être géocodée.</p>
    </div>
  <% end %>

  <!-- Card pour le calendrier -->
  <div class="card shadow-sm p-3 mt-5 bg-white rounded">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4 class="text-primary fw-bold"><%= (@plant.price) %>€ par jour</h4>
    </div>
    <div class="form-group" data-controller="dynamic-booking-price" data-dynamic-booking-price-price-value="<%= @plant.price %>">
      <%= simple_form_for([@plant, @renting], html: { data: { controller: 'datepicker' } }) do |f| %>
        <div class="mb-3">
          <%= f.input :start_date, as: :string, label: "Date de début :", input_html: {
            class: "form-control text-center",
            data: {
              datepicker_target: 'startDateInput',
              dynamic_booking_price_target: 'startDateInput',
              action: 'change->dynamic-booking-price#updatePrice'
            }
          } %>
        </div>
        <div class="mb-3">
          <%= f.input :end_date, as: :string, label: "Date de fin :", input_html: {
            class: "form-control text-center",
            data: {
              datepicker_target: 'endDateInput',
              dynamic_booking_price_target: 'endDateInput',
              action: 'change->dynamic-booking-price#updatePrice'
            }
          } %>
        </div>
        <% if @plant.user != @user %>
          <div class="d-grid">
            <%= f.submit 'Réserver', class: 'btn btn-primary btn-lg mb-2 p-0' %>
          </div>
        <% end %>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <h5>Total</h5>
          <h4><span data-dynamic-booking-price-target="priceHolder"><%=(@plant.price) %>€</span></h4>
        </div>
      <% end %>
    </div>
  </div>
</div>


      </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top">
  <div class="container-fluid d-flex align-items-center justify-content-between">
    <%= link_to root_path do %>
      <button class="navbar-brand-btn">Planty</button>
    <% end %>
    <div class="container-button d-flex align-items-center">
      <%= link_to new_plant_path  do %>
        <button class="create-btn"> Créer une annonce </button>
      <% end %>
      <%= link_to dashboard_path do %>
        <button class="profil-btn"></button>
      <% end%>
    </div>
  </div>
</nav>